[package]
name = "inline_gzip"
version = "0.1.0"
authors = ["Roderick Bovee <roderick@onecodex.com>"]
edition = "2018"

[dependencies]
criterion = "0.3"
flate2 = "1.0.6"

[[bench]]
path = "src/lib.rs"
name = "benches"
harness = false
